# Generated by Django 3.0.2 on 2020-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=305)),
                ('text', models.TextField()),
                ('image', models.ImageField(height_field=1920, upload_to='images/', width_field=1080)),
                ('icon', models.ImageField(height_field=500, upload_to='icons/', width_field=500)),
            ],
        ),
    ]
