# Generated by Django 3.0.2 on 2020-01-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(height_field=500, upload_to='static/icons/', width_field=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(height_field=1920, upload_to='static/images/', width_field=1080),
        ),
    ]
