# Generated by Django 3.0.2 on 2020-01-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200119_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
