# Generated by Django 3.0.2 on 2020-01-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200119_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon2',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
